apiVersion: v2
name: flagr
description: A Helm chart for Flagr, a feature flagging and configuration management platform.
type: application

version: 1.17.0-beta
appVersion: "1.17.0"

maintainers:
  - name: Eric Santana
    email: bitencourteric@hotmail.com
    url: https://ericbsantana.com

sources:
  - https://github.com/ericbsantana/flagr-helm-chart
