name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release Chart
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache helm-docs binary
        id: cache-binary
        uses: actions/cache@v3
        with:
          path: ~/.local/bin/helm-docs
          key: ${{ runner.os }}-helm-docs-v1.14.2

      - name: Download and install binary
        if: steps.cache-binary.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/.local/bin
          curl -L "https://github.com/norwoodj/helm-docs/releases/download/v1.14.2/helm-docs_1.14.2_Linux_x86_64.tar.gz" -o helm-docs-v1.14.2
          tar -xzf helm-docs-v1.14.2
          mv ./helm-docs ~/.local/bin/helm-docs
          rm helm-docs-v1.14.2 LICENSE README.md CHANGELOG.md
          chmod +x ~/.local/bin/helm-docs

      - name: Add binary to PATH
        run: echo "~/.local/bin" >> $GITHUB_PATH

      - name: Generate docs
        run: helm-docs

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Commit changes
        run: |
          git add charts/flagr/README.md
          git commit -m "docs: update docs"
          git push

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          skip_existing: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
